<div style="width: 100%; clear: both;">
    <div style="float: left; width: 50%;">
       <img src="https://www.uoc.edu/portal/system/modules/edu.uoc.presentations/resources/img/branding/logo-uoc-default.png", align="left">
    </div>
</div>

<div style="float: right; width: 50%;">
    <p style="margin: 0; text-align:right;">22.503 · Programación para la ciencia de datos</p>
    <p style="margin: 0; text-align:right;">Grado en Ciencia de Datos Aplicada</p>
    <p style="margin: 0; text-align:right; padding-button: 100px;">Estudios de Informática, Multimedia y Telecomunicaciones</p>
</div>

</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;"> </div>

Programación para la ciencia de datos - PEC1
============================

En este Notebook encontraréis un conjunto de ejercicios que conforman la primera actividad de evaluación continua (PEC) de la asignatura.

Para cada ejercicio, tened en cuenta que:  

* **Es necesario incluir comentarios** de vuestro código, que expliquen cómo ha implementado la solución del problema planteado.  
* **Es imprescindible** citar las referencias consultadas para realizar la actividad. Se valorará que el código proporcionado solucione el problema propuesto y también la calidad del código (comentarios, legibilidad, claridad, uso de las estructuras de datos adecuadas, buena nomenclatura de las variables y funciones, seguimiento del PEP8, etc. ).

Veréis que cada una de las actividades tiene asociada una puntuación, que indica el peso que tiene la actividad sobre la nota de la PEC.

Además, todas las actividades tienen una etiqueta, que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:
* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span>   **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura (consideraremos también los materiales de la asignatura Fundamentos de Programación, así como las lecturas obligatorias de material externo que se indican en los notebooks).  
* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.  
* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span> **Consulta externa independiente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recuerde que las **etiquetas son informativas**, pero puede consultar referencias externas siempre que lo desee (aunque no se indique explícitamente) o puede que pueda realizar una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puede consultar referencias externas si se desea, ya sea tanto para ayudar en la resolución como para ampliar conocimientos.


---

## Antes de empezar

Leed atentamente los parágrafos que siguen, relacionados con la originalidad en las actividades, antes de empezar a trabajar en la PEC. Si os surge cualquier duda dirigiros al profesor colaborador de la asignatura antes de continuar con la actividad.

<div class="alert alert-block alert-success"> La falta de originalidad se produce cuando en una actividad aparece contenido que no ha sido elaborado de forma individual por el estudiante y no se referencia adecuadamente su origen. O bien cuando, aunque el contenido externo esté referenciado, este es tan extenso que no es posible considerar al estudiante el autor o autora de la actividad.

Así, algunos ejemplos de comportamientos inadecuados debido a falta de originalidad son:

- Crear la solución de un ejercicio de la PEC en colaboración entre diversos estudiantes.
- Incluir un ejercicio de la PEC que utiliza código encontrado en internet sin citar la fuente.
- Compartir vuestra solución de la PEC con otros estudiantes de la asignatura.
- El uso abusivo de herramientas de inteligencia artificial que realicen la tarea.

## Instrucciones generales

- Lee atentamente cada enunciado antes de programar.
- Utiliza nombres de variables y funciones claros.
- Añade comentarios cuando sean útiles para explicar decisiones relevantes.
- Se valorará el uso correcto de tipos (`type hints`), nombres descriptivos y estilo PEP8.
- No vuelvas a cargar el fichero CSV en ejercicios posteriores: reutiliza el `DataFrame` creado en el ejercicio 1.
- Si consultas documentación externa, indica las fuentes utilizadas.

## Type hints

Os recomendamos resolver esta PEC usando type hints. Podemos entender los type hints de Python como una solución formal para indicar estéticamente el tipo de valor dentro del código Python. Os recomendamos la visualización del siguiente [vídeo](https://www.youtube.com/watch?v=j0dy8Q9VIPk) para una introducción a los type hints en Python, y para entender por qué son interesantes.

# Ejercicio 1

Una empresa de bicicletas compartidas mantiene información de las estaciones y de las bicicletas disponibles.

```python
estaciones = ["BCN01", "BCN02", "BCN03", "BCN04", "BCN05"]
estaciones_activas = ["BCN01", "BCN03", "BCN04"]
bicicletas = [
    {"id": "B001", "estacion": "BCN01", "tipo": "electrica"},
    {"id": "B002", "estacion": "BCN02", "tipo": "mecanica"},
    {"id": "B003", "estacion": "BCN03", "tipo": "electrica"},
    {"id": "B004", "estacion": "BCN03", "tipo": "mecanica"},
    {"id": "B005", "estacion": "BCN04", "tipo": "electrica"},
    {"id": "B006", "estacion": "BCN05", "tipo": "mecanica"}
]
```

**Tareas:**

1. Obtén las estaciones que aparecen en los datos de bicicletas.
2. Obtén las estaciones que están activas y que además tienen alguna bicicleta registrada.
3. Mediante una comprensión de diccionario, crea un diccionario que tenga como clave el identificador de la bicicleta y como valor su tipo.
4. Crea una lista con los identificadores de las bicicletas eléctricas que pertenecen a estaciones activas.

SM **(2 puntos)**

In [1]:
%load_ext pycodestyle_magic

In [2]:
# Activamos las alertas de estilo
%pycodestyle_on

In [3]:
# Escribe aquí tu solución.

estaciones: list[str] = ["BCN01", "BCN02", "BCN03", "BCN04", "BCN05"]
estaciones_activas: list[str] = ["BCN01", "BCN03", "BCN04"]
bicicletas: list[dict[str, str]] = [
    {"id": "B001", "estacion": "BCN01", "tipo": "electrica"},
    {"id": "B002", "estacion": "BCN02", "tipo": "mecanica"},
    {"id": "B003", "estacion": "BCN03", "tipo": "electrica"},
    {"id": "B004", "estacion": "BCN03", "tipo": "mecanica"},
    {"id": "B005", "estacion": "BCN04", "tipo": "electrica"},
    {"id": "B006", "estacion": "BCN05", "tipo": "mecanica"}
]

In [4]:
# Tarea 1. Obtén las estaciones que aparecen en los datos de bicicletas.

# Utilizamos la propiedad de contener valores únicos de los conjuntos(set) y
# la comprensión de conjuntos para extraer todos los valores de la clave
# "estacion" de todas las bicicletas y guardarlos en un conjunto(set) llamado
# estaciones_en_bicicletas
estaciones_con_bicicletas: set[str] = {
    bicicleta["estacion"] for bicicleta in bicicletas
    }

# Tenemos en cuenta que puede ocurrir que ninguna de las estaciónes aparezcan
# en los datos de bicicletas, por lo que comprobamos si el conjunto(set) de
# estaciones_con_bicicletas está vacío, es decir, no hay estaciones con
# bicicletas. Así, si es el caso, en vez de mostrar un mensaje con una lista
# vacía, mostramos un mensaje indicando que no hay estaciones con bicicletas.
if (len(estaciones_con_bicicletas) == 0):
    print("No hay estaciones que aparezcan en los datos de bicicletas.")
else:
    # mostramos el resultado
    # (ordenamos las estaciones para que se vea más bonito)
    print("Las estaciones que aparecen en los datos de bicicletas son:",
          sorted(estaciones_con_bicicletas))

Las estaciones que aparecen en los datos de bicicletas son: ['BCN01', 'BCN02', 'BCN03', 'BCN04', 'BCN05']

In [5]:
# Tarea 2. Obtén las estaciones que no aparecen en los datos de bicicletas.

# Aprovechamos que ya tenemos un conjunto(set) con todas las estaciones que
# aparecen en los datos de bicicletas y una lista con todas las estaciones
# existentes y excluyendo las que aparecen de la lista de todas, obtenemos
# las que no aparecen.
estaciones_sin_bicicletas: set[str] = (
    set(estaciones) - estaciones_con_bicicletas
)
# Tenemos en cuenta que puede ocurrir que todas las estaciónes aparezcan en
# los datos de bicicletas, por lo que comprobamos si el conjunto(set) de
# estaciones_sin_bicicletas está vacío, es decir, no hay estaciones sin
# bicicletas. Así, si es el caso, en vez de mostrar un mensaje con una lista
# vacía, mostramos un mensaje indicando que no hay estaciones sin bicicletas.
if (len(estaciones_sin_bicicletas) == 0):
    print("No hay estaciones que no aparezcan en los datos de bicicletas.")
else:
    # mostramos el resultado
    # (ordenamos las estaciones para que se vea más bonito)
    print("Las estaciones que no aparecen en los datos de bicicletas son:",
          sorted(estaciones_sin_bicicletas))

No hay estaciones que no aparezcan en los datos de bicicletas.

In [6]:
# 3. Mediante una comprensión de diccionario, crea un diccionario que tenga
# como clave el identificador de la bicicleta y como valor su tipo.

# Importamos esta librería para mostrar de
# manera más clara el diccionario resultante
import pprint

# Utilizamos la comprensión de diccionarios para generar nuevo diccionario
# comprimido {clave: valor for elemento in diccionario}.
# Seleccionando como clave el id de la bicicleta y como valor su tipo
bicicletas_por_tipo: dict[str, str] = {
    bicicleta["id"]: bicicleta["tipo"] for bicicleta in bicicletas
    }

# Utilizamos la librería pprint para mostrar
# de manera más clara el diccionario resultante
print("Diccionario con el id de la bicicleta como clave y su tipo como valor:")
pprint.pprint(bicicletas_por_tipo)

Diccionario con el id de la bicicleta como clave y su tipo como valor:
{'B001': 'electrica',
 'B002': 'mecanica',
 'B003': 'electrica',
 'B004': 'mecanica',
 'B005': 'electrica',
 'B006': 'mecanica'}

In [7]:
# 4. Crea una lista con los identificadores de las bicicletas
# eléctricas que pertenecen a estaciones activas.

# Utilizamos la comprensión de listas
# [valor for elemento in diccionario if condicion]
# usando una condición(if) para extraer solo las bicicletas
# eléctricas y la estación de las cuales está incluida en la
# lista de estaciones activas, es decir, está en una estación activa.
# como resultado obtenemos una lista con los ids (bicicleta["id"])
# de las bicicletas con las condiciones del enunciado.
bicis_electric_activa: list[str] = [
    bicicleta["id"] for bicicleta in bicicletas
    if bicicleta["tipo"] == "electrica"
    and bicicleta["estacion"] in estaciones_activas]

# Mostramos el resultado
print(f"Ids de las bicicletas eléctricas que pertenecen a estaciones activas:\
\n{bicis_electric_activa}")

Ids de las bicicletas eléctricas que pertenecen a estaciones activas:
['B001', 'B003', 'B005']

# Ejercicio 2

El fichero `alquileres_bicicletas.csv` contiene registros de alquileres. Las columnas son:

- `id_alquiler`
- `fecha`
- `estacion`
- `duracion_min`

**Tareas:**

1. Lee el fichero en un `DataFrame` utilizando Pandas.
2. Muestra las dimensiones del `DataFrame` y los tipos de datos de sus columnas.
3. Comprueba si existen valores nulos e identifica en qué columnas aparecen.
4. Convierte la columna `fecha` al tipo de fecha apropiado.
5. Identifica los registros cuya `duracion_min` no sea válida (valor nulo o menor o igual que cero).
6. Crea una nueva columna `duracion_horas` a partir de `duracion_min`.
7. Crea una copia limpia eliminando los registros con una duración no válida.

SM **(2 puntos)**

In [8]:
# Escribe aquí tu solución.
import pandas as pd

alq_bic = pd.read_csv('./data/alquileres_bicicletas.csv')

In [9]:
alq_bic.head(5)

     id                fecha estacion  duracion_min
0  A001  2025-05-02 23:00:00    BCN02           8.0
1  A002  2025-05-02 04:00:00    BCN04          33.0
2  A003  2025-05-01 23:00:00    BCN02          91.0
3  A004  2025-05-03 05:00:00    BCN02          80.0
4  A005  2025-05-03 02:00:00    BCN01           8.0

In [10]:
filas = alq_bic.shape[0]
columnas = alq_bic.shape[1]

print(f'El DataFrame tiene: {filas} filas {columnas} columnas\n')
print('Columna: Tipo')
for c, t in alq_bic.dtypes.to_dict().items():
    print(f'{c}: {t}')

8:1: W391 blank line at end of file

El DataFrame tiene: 60 filas 4 columnas

Columna: Tipo
id: object
fecha: object
estacion: object
duracion_min: float64

In [11]:
for c in alq_bic.columns:
    if alq_bic[c].isnull().any():
        print(f'La columna {c} tiene valores nulos en estos registros:')
        print(alq_bic[alq_bic[c].isnull()])
    else:
        print(f'La columna {c} no tiene valores nulos')

La columna id no tiene valores nulos
La columna fecha no tiene valores nulos
La columna estacion no tiene valores nulos
La columna duracion_min tiene valores nulos en estos registros:
      id                fecha estacion  duracion_min
7   A008  2025-05-02 23:00:00    BCN07           NaN
19  A020  2025-05-04 23:00:00    BCN02           NaN
43  A044  2025-05-08 14:00:00    BCN02           NaN

In [12]:
alq_bic['fecha'] = pd.to_datetime(alq_bic['fecha'], format='%Y-%m-%d %H:%M:%S')

In [16]:
alq_bic[(alq_bic['duracion_min']<0) | (alq_bic['duracion_min'].isna())]

      id               fecha estacion  duracion_min
7   A008 2025-05-02 23:00:00    BCN07           NaN
12  A013 2025-05-04 04:00:00    BCN02          -2.0
19  A020 2025-05-04 23:00:00    BCN02           NaN
31  A032 2025-05-07 07:00:00    BCN01          -4.0
43  A044 2025-05-08 14:00:00    BCN02           NaN
52  A053 2025-05-11 04:00:00    BCN01         -12.0

1:33: E225 missing whitespace around operator

In [29]:
alq_bic['duracion_horas'] = (alq_bic['duracion_min']/60).__round__(3)
alq_bic.head()

     id               fecha estacion  duracion_min  duracion_horas
0  A001 2025-05-02 23:00:00    BCN02           8.0           0.133
1  A002 2025-05-02 04:00:00    BCN04          33.0           0.550
2  A003 2025-05-01 23:00:00    BCN02          91.0           1.517
3  A004 2025-05-03 05:00:00    BCN02          80.0           1.333
4  A005 2025-05-03 02:00:00    BCN01           8.0           0.133

In [35]:
alq_bic_limpia = alq_bic[~((alq_bic['duracion_min'] < 0)
                         | (alq_bic['duracion_min'].isna()))].copy()
alq_bic_limpia

      id               fecha estacion  duracion_min  duracion_horas
0   A001 2025-05-02 23:00:00    BCN02           8.0           0.133
1   A002 2025-05-02 04:00:00    BCN04          33.0           0.550
2   A003 2025-05-01 23:00:00    BCN02          91.0           1.517
3   A004 2025-05-03 05:00:00    BCN02          80.0           1.333
4   A005 2025-05-03 02:00:00    BCN01           8.0           0.133
5   A006 2025-05-02 08:00:00    BCN04          34.0           0.567
6   A007 2025-05-03 15:00:00    BCN01          76.0           1.267
8   A009 2025-05-03 05:00:00    BCN08          80.0           1.333
9   A010 2025-05-03 12:00:00    BCN01         102.0           1.700
10  A011 2025-05-03 09:00:00    BCN07          48.0           0.800
11  A012 2025-05-03 20:00:00    BCN03          32.0           0.533
13  A014 2025-05-04 11:00:00    BCN02          50.0           0.833
14  A015 2025-05-04 13:00:00    BCN05         108.0           1.800
15  A016 2025-05-03 21:00:00    BCN08          73.0           1.217
16  A017 2025-05-04 06:00:00    BCN07          15.0           0.250
17  A018 2025-05-05 14:00:00    BCN05         111.0           1.850
18  A019 2025-05-05 23:00:00    BCN06          78.0           1.300
20  A021 2025-05-04 17:00:00    BCN04         103.0           1.717
21  A022 2025-05-05 13:00:00    BCN02         114.0           1.900
22  A023 2025-05-05 13:00:00    BCN02          53.0           0.883
23  A024 2025-05-05 20:00:00    BCN08          86.0           1.433
24  A025 2025-05-06 06:00:00    BCN03          52.0           0.867
25  A026 2025-05-06 09:00:00    BCN04          90.0           1.500
26  A027 2025-05-06 08:00:00    BCN02          82.0           1.367
27  A028 2025-05-07 11:00:00    BCN03          73.0           1.217
28  A029 2025-05-06 14:00:00    BCN03          64.0           1.067
29  A030 2025-05-07 03:00:00    BCN05          86.0           1.433
30  A031 2025-05-08 03:00:00    BCN04          92.0           1.533
32  A033 2025-05-06 17:00:00    BCN06          56.0           0.933
33  A034 2025-05-07 12:00:00    BCN02          32.0           0.533
34  A035 2025-05-08 11:00:00    BCN06          32.0           0.533
35  A036 2025-05-08 20:00:00    BCN08          55.0           0.917
36  A037 2025-05-09 00:00:00    BCN08          23.0           0.383
37  A038 2025-05-08 03:00:00    BCN03          36.0           0.600
38  A039 2025-05-09 02:00:00    BCN05         100.0           1.667
39  A040 2025-05-09 08:00:00    BCN07         119.0           1.983
40  A041 2025-05-09 12:00:00    BCN07          51.0           0.850
41  A042 2025-05-08 17:00:00    BCN03          70.0           1.167
42  A043 2025-05-09 14:00:00    BCN02         101.0           1.683
44  A045 2025-05-09 00:00:00    BCN03         106.0           1.767
45  A046 2025-05-10 14:00:00    BCN07          81.0           1.350
46  A047 2025-05-09 03:00:00    BCN07          53.0           0.883
47  A048 2025-05-10 17:00:00    BCN08          72.0           1.200
48  A049 2025-05-09 23:00:00    BCN01          92.0           1.533
49  A050 2025-05-09 18:00:00    BCN05         103.0           1.717
50  A051 2025-05-11 08:00:00    BCN06          19.0           0.317
51  A052 2025-05-10 13:00:00    BCN07          25.0           0.417
53  A054 2025-05-10 19:00:00    BCN03          69.0           1.150
54  A055 2025-05-10 13:00:00    BCN05         112.0           1.867
55  A056 2025-05-12 03:00:00    BCN04          24.0           0.400
56  A057 2025-05-11 14:00:00    BCN03          74.0           1.233
57  A058 2025-05-12 04:00:00    BCN01          81.0           1.350
58  A059 2025-05-11 19:00:00    BCN08           7.0           0.117
59  A060 2025-05-11 10:00:00    BCN06         117.0           1.950

# Ejercicio 3

A partir de una lista de alquileres representados como diccionarios, se quiere construir un resumen por estación de origen.

```python
alquileres = [
    {"estacion": "BCN01", "tipo": "electrica", "duracion": 25},
    {"estacion": "BCN02", "tipo": "mecanica", "duracion": 18},
    {"estacion": "BCN01", "tipo": "mecanica", "duracion": 32},
    {"estacion": "BCN03", "tipo": "electrica", "duracion": 41},
    {"estacion": "BCN02", "tipo": "electrica", "duracion": 22},
    {"estacion": "BCN01", "tipo": "electrica", "duracion": 27}
]
```

**Tareas:**

1. Escribe una función `resumen_estaciones(alquileres)` que utilice `defaultdict` para agrupar las duraciones por estación.
2. La función debe devolver un diccionario donde cada estación tenga asociada la lista de duraciones de sus alquileres.
3. A partir del resultado, calcula el número de alquileres de cada estación.
4. Utiliza `OrderedDict` para devolver las estaciones ordenadas de mayor a menor número de alquileres.

SM **(2 puntos)**

In [1]:
# Escribe aquí tu solución.

alquileres = [
    {"estacion": "BCN01", "tipo": "electrica", "duracion": 25},
    {"estacion": "BCN02", "tipo": "mecanica", "duracion": 18},
    {"estacion": "BCN01", "tipo": "mecanica", "duracion": 32},
    {"estacion": "BCN03", "tipo": "electrica", "duracion": 41},
    {"estacion": "BCN02", "tipo": "electrica", "duracion": 22},
    {"estacion": "BCN01", "tipo": "electrica", "duracion": 27}
]

In [2]:
from collections import defaultdict

dur_por_est = defaultdict(list)

def resumen_estaciones(alquileres: list) -> dict:
    for alquiler in alquileres:
        estacion: str = alquiler['estacion']
        dur_por_est[estacion].append(alquiler['duracion'])
    return dur_por_est

resumen_est = resumen_estaciones(alquileres)
resumen_est

defaultdict(list, {'BCN01': [25, 32, 27], 'BCN02': [18, 22], 'BCN03': [41]})

In [3]:
alq_por_est: dict = {}
for est, list_dur in resumen_est.items():
    alq_por_est[est] = len(list_dur)

alq_por_est

{'BCN01': 3, 'BCN02': 2, 'BCN03': 1}

In [43]:
from collections import OrderedDict

ord_alq_por_est = OrderedDict(alq_por_est)
ord_alq_por_est

OrderedDict([('BCN01', 3), ('BCN02', 2), ('BCN03', 1)])

# Ejercicio 4

Se quiere analizar la duración de determinados alquileres a partir de sus instantes de inicio y finalización.

```python
inicio = "2025-05-14 08:35:00"
fin = "2025-05-14 09:12:30"
```

**Tareas:**

1. Convierte las dos cadenas a objetos `datetime`.
2. Calcula la duración del alquiler mediante una resta entre fechas.
3. Obtén la duración expresada en minutos y segundos.
4. Utiliza `timedelta` para determinar la hora de finalización de un alquiler que comienza a las 18:45:00 y dura 75 minutos.
5. Escribe una función `es_alquiler_largo(inicio, fin, limite=30)` que devuelva `True` si la duración supera el límite indicado en minutos.

SM **(2 puntos)**

In [ ]:
# Escribe aquí tu solución.
import datetime

inicio: str = "2025-05-14 08:35:00"
fin:str = "2025-05-14 09:12:30"

inicio_dt: datetime = datetime.datetime.strptime(inicio, "%Y-%m-%d %H:%M:%S")
fin_dt: datetime = datetime.datetime.strptime(fin, "%Y-%m-%d %H:%M:%S")

duracion = fin_dt - inicio_dt
minutos: int = (int)(duracion.total_seconds() / 60)
segundos: int = (int)((duracion.total_seconds() / 60 - minutos) * 60)

print(f"La duracion es de {minutos} minutos y {segundos} segundos")

La duracion es de 37 minutos y 30 segundos

In [ ]:
inicio_alq: datetime.datetime = datetime.datetime(year=2025, month=5, day=14,
                               hour=18, minute=45, second=0)
duracion_alq: datetime.timedelta = datetime.timedelta(minutes=75)
fin_alq: datetime.datetime = inicio_alq + duracion_alq
datetime.datetime.strftime(fin_alq, "%H:%M:%S")

'20:00:00'

In [ ]:
def es_alquiler_largo(inicio, fin, limite=30) -> bool:
    return (fin - inicio).total_seconds() / 60 > limite

es_alquiler_largo(inicio_dt, fin_dt)

False

# Ejercicio 5

La empresa quiere representar cada estación mediante un objeto. Una estación tiene un identificador, una capacidad máxima y un número de bicicletas disponibles.

El identificador debe seguir el formato `EST-` seguido de dos letras mayúsculas y dos dígitos, por ejemplo `EST-BC01`.

**Tareas:**

1. Crea una clase `Estacion` con los atributos `identificador`, `capacidad` y `bicicletas_disponibles`.
2. En el constructor, valida mediante una expresión regular que el identificador tenga el formato correcto. Si no lo tiene, debe producirse una excepción apropiada.
3. Implementa un método `porcentaje_ocupacion()` que devuelva el porcentaje de ocupación de la estación.
4. Implementa un método `necesita_redistribucion()` que devuelva `True` cuando el porcentaje de ocupación sea inferior al 20 % o superior al 90 %.
5. Implementa un método `resumen()` que devuelva una cadena con la información principal de la estación.
6. Crea varios objetos `Estacion` y prueba todos los métodos.
7. Incluye al menos un identificador incorrecto y comprueba que la validación funciona correctamente.

SM **(2 puntos)**

In [90]:
# Escribe aquí tu solución.
import re

class Estacion:
    def __init__(self, identificador: str, capacidad: int, bicicletas_disponibles: int) -> "Estacion":
        if re.fullmatch(r'EST-[A-Z]{2}\d{2}', identificador) != None:
            self.identificador = identificador
        else:
            raise Exception(f"El identificador debe seguir el formato \'EST- seguido\' de dos letras mayúsculas y dos dígitos, por ejemplo \'EST-BC01\'.")
        self.capacidad = capacidad
        self.bicicletas_disponibles = bicicletas_disponibles

    def porcentaje_ocupacion(self):
        return (self.bicicletas_disponibles) / (self.capacidad) * 100
    
    def necesita_redistribucion(self):
        return (self.porcentaje_ocupacion() < 20 or self.porcentaje_ocupacion() > 90)
    
    def resmen(self):
        mensaje = f"""identificador: {self.identificador}
capacidad: {self.capacidad}
bicicletas disponibles: {self.bicicletas_disponibles}
"""
        return mensaje
estacion1 = Estacion("EST-BC11", 200, 50)
estacion1.porcentaje_ocupacion()
print(estacion1.resmen())

identificador: EST-BC11
capacidad: 200
bicicletas disponibles: 50